- name: Reboot NAT if required (Amazon Linux)
  hosts: ssm_nat
  gather_facts: false
  become: true

  tasks:
    - name: Check if reboot is required (Amazon Linux)
      ansible.builtin.command: needs-restarting -r
      register: reboot_check
      changed_when: false
      failed_when: reboot_check.rc not in [0, 1]

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 10
        test_command: whoami
      when: reboot_check.rc == 1
      