- name: Update and Upgrade
  hosts: ssm_hosts,ssm_nat
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Install locales-all
      ansible.builtin.apt:
        name: locales-all
        state: present

    - name: Ensure en_US.UTF-8 locale exists
      ansible.builtin.locale_gen:
        name: en_US.UTF-8
        state: present   
        